std_msgs/Bool demo
fh_utils/GraspMsg[] grasps
std_msgs/Int32MultiArray objects
std_msgs/Int32MultiArray masks
sensor_msgs/PointCloud2 cloud
std_msgs/Float32MultiArray cloud_uv
---
fh_utils/GraspMsg[] grasps
